site_name: MovieDataset
nav:
    - Home: index.md
    - RDlite: rdlite.md
    - MovieClean: movieClean.md
    - dashProject: dashpro.md

theme: readthedocs

plugins:
- mkdocstrings:
    handlers:
        python:
            paths: [.., ../MovieClean]
            rendering:
                show_source: false

watch:
    - ../RDlite
    - ../MovieClean/MovieClean
    - ../dashProject